--- 
development:
  :wheel_id: 1
  :garbage_id: 1
  :public_rule: 208
  
staging:
  :wheel_id: ~
  
test:
  :wheel_id: 690249644
  :garbage_id: 690249644
  :public_rule: 491014080

production:
  :wheel_id: 1
  :garbage_id: 3
  :public_rule: 189
