--- 
:load_all_initially: true
:scripts_at_bottom: true
:defcon: 0
:enable_debugger: false
:disable_registration: true
:disable_search: true
:disable_akismet: true
:disable_google_ads: true
:disable_comments: false
:disable_anonymous_comments: false
