development:
  bucket_name: juscribe
  access_key_id: 11TRWSM15ZY66E9YXRR2
  secret_access_key: JyFbY1qTWr/Jmtgp+8rj+SiPxPfxXFWA1a+VfIlM

test:
  bucket_name: juscribe
  access_key_id: 11TRWSM15ZY66E9YXRR2
  secret_access_key: JyFbY1qTWr/Jmtgp+8rj+SiPxPfxXFWA1a+VfIlM

production:
  bucket_name: juscribe
  access_key_id: 11TRWSM15ZY66E9YXRR2
  secret_access_key: JyFbY1qTWr/Jmtgp+8rj+SiPxPfxXFWA1a+VfIlM
