---
user: colin
group: colin
log_file: log/mongrel.log
cwd: /home/colin/public_html/juscribe.com/current/
port: 3000
environment: production
pid_file: tmp/pids/mongrel.pid
address: 127.0.0.1
servers: 3
